litemall:
  # 开发者应该设置成自己的wx相关信息
  wx:
    app-id: wx1eedfb8d81a3244b
    app-secret: b9a76091f0e1a441d4d3727085367dab
    mch-id: 111111
    mch-key: xxxxxx
    notify-url: https://www.zhangcde.asia/wx/order/pay-notify
    # 商户证书文件路径
    # 请参考“商户证书”一节 https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=4_3
    key-path: xxxxx
    # 消息推送配置token
    token:
    # 消息推送配置AesKey
    aes-key:

  #通知相关配置
  notify:
    mail:
      # 邮件通知配置,邮箱一般用于接收业务通知例如收到新的订单，sendto 定义邮件接收者，通常为商城运营人员
      enable: false
      host: smtp.exmail.qq.com
      username: ex@ex.com.cn
      password: XXXXXXXXXXXXX
      sendfrom: ex@ex.com.cn
      sendto: ex@qq.com
      port: 465
    # 短消息模版通知配置
    # 短信息用于通知客户，例如发货短信通知，注意配置格式；template-name，template-templateId 请参考 NotifyType 枚举值
    sms:
      enable: false
      # 如果是腾讯云短信，则设置active的值tencent
      # 如果是阿里云短信，则设置active的值aliyun
      active: tencent
      sign: litemall
      template:
      - name: paySucceed
        templateId: 156349
      - name: captcha
        templateId: 156433
      - name: ship
        templateId: 158002
      - name: refund
        templateId: 159447
      tencent:
        appid: 111111111
        appkey: xxxxxxxxxxxxxx
      aliyun:
        regionId: xxx
        accessKeyId: xxx
        accessKeySecret: xxx

  # 快鸟物流查询配置
  express:
    enable: true
    appId: 1912788
    appKey: 3e1ce226-8749-4266-8cef-bb3e6234ec4c
    vendors:
    - code: "ZTO"
      name: "中通快递"
    - code: "YTO"
      name: "圆通速递"
    - code: "YD"
      name: "韵达速递"
    - code: "STO"
      name: "申通快递"
    - code: "SF"
      name: "顺丰速运"
    - code: "JD"
      name: "京东快递"
    - code: "YZPY"
      name: "邮政快递包裹"
    - code: "EMS"
      name: "EMS"
    - code: "JTSD"
      name: "极兔速递"
    - code: "DBL"
      name: "德邦快递"
    - code: "FWX"
      name: "丰网速运"
    - code: "HTKY"
      name: "百世快递"
    - code: "DNWL"
      name: "东骏快捷物流"
    - code: "FEDEX"
      name: "FEDEX联邦（国内）"
    - code: "RRS"
      name: "日日顺物流"
    - code: "ANEKY"
      name: "安能快运/物流"
    - code: "ZTOKY"
      name: "中通快运"
    - code: "ANE"
      name: "安能快递"
    - code: "SX"
      name: "顺心捷达"
    - code: "BTWL"
      name: "百世快运"
    - code: "XFEX"
      name: "信丰物流"
    - code: "YMDD"
      name: "壹米滴答"
    - code: "JGSD"
      name: "京广速递"
    - code: "DBLKY"
      name: "德邦快运/德邦物流"
    - code: "KYSY"
      name: "跨越速运"
    - code: "JDKY"
      name: "京东快运"
    - code: "YDKY"
      name: "韵达快运"
    - code: "TJS"
      name: "特急送"
    - code: "UPS"
      name: "UPS"
    - code: "YAD"
      name: "源安达快递"
    - code: "ANNTO"
      name: "安得物流"
    - code: "LHT"
      name: "联昊通速递"
    - code: "ZJS"
      name: "宅急送"
    - code: "YF"
      name: "耀飞快递"
    - code: "USPS"
      name: "USPS美国邮政"
    - code: "DHL"
      name: "DHL-中国件"
    - code: "FASTGO"
      name: "速派快递"
    - code: "HSSY"
      name: "汇森速运"
    - code: "JYM"
      name: "加运美"
    - code: "ZTOGLOBAL"
      name: "中通国际"
    - code: "UC"
      name: "优速快递"
    - code: "HOAU"
      name: "天地华宇"
    - code: "TNJEX"
      name: "明通国际快递"
    - code: "DPDUK"
      name: "DPD(UK)"
    - code: "DSWL"
      name: "D速物流"
    - code: "EWE"
      name: "EWE"
    - code: "SHWL"
      name: "盛辉物流"
    - code: "YJWL"
      name: "云聚物流"
    - code: "ZY_FY"
      name: "飞洋快递"
    - code: "YXWL"
      name: "宇鑫物流"
    - code: "PADTF"
      name: "平安达腾飞快递"
    - code: "ZYE"
      name: "众邮快递"
    - code: "UBONEX"
      name: "优邦国际速运"
    - code: "ZHONGTIEWULIU"
      name: "中铁飞豹"
    - code: "HDWL"
      name: "宏递快运"
    - code: "CRAZY"
      name: "疯狂快递"
    - code: "STWL"
      name: "速腾快递"
    - code: "CTWL"
      name: "长通物流"
    - code: "PANEX"
      name: "泛捷快递"
    - code: "LB"
      name: "龙邦快递"
    - code: "BETWL"
      name: "百腾物流"
    - code: "AUEXPRESS"
      name: "澳邮中国快运AuExpress"
    - code: "ESDEX"
      name: "卓志速运"
    - code: "SFWL"
      name: "盛丰物流"
    - code: "JP"
      name: "日本邮政"
    - code: "ZY100"
      name: "中远快运"
    - code: "HTB56"
      name: "徽托邦物流"
    - code: "YBG"
      name: "洋包裹"
    - code: "ZTWL"
      name: "中铁物流"
    - code: "ZHONGHUAN"
      name: "中环国际快递"
    - code: "HTWL"
      name: "鸿泰物流"
    - code: "BCTWL"
      name: "百城通物流"
    - code: "SNWL"
      name: "苏宁物流"
    - code: "TU"
      name: "运联科技"
    - code: "TBZS"
      name: "特宝专送"
    - code: "FTD"
      name: "富腾达"
    - code: "JIUYE"
      name: "九曳供应链"
    - code: "CSTD"
      name: "畅顺通达"
    - code: "HISENSE"
      name: "海信物流"
    - code: "AUODEXPRESS"
      name: "澳德物流"
    - code: "GJYZBG"
      name: "国际邮政包裹"
    - code: "YLFWL"
      name: "一路发物流"
    - code: "WHXBWL"
      name: "武汉晓毕物流"
    - code: "YSDF"
      name: "余氏东风"
    - code: "JAD"
      name: "捷安达"
    - code: "AUEX"
      name: "澳货通"
    - code: "SUBIDA"
      name: "速必达物流"
    - code: "SYJWDX"
      name: "佳旺达物流"
    - code: "ROYALMAIL"
      name: "RoyalMail"
    - code: "FZGJ"
      name: "方舟国际速递"
    - code: "XJ"
      name: "新杰物流"
    - code: "TNT"
      name: "TNT国际快递"
    - code: "SENDCN"
      name: "速递中国"
    - code: "EMSBG"
      name: "EMS包裹"
    - code: "DTWL"
      name: "大田物流"
    - code: "D4PX"
      name: "递四方速递"
    - code: "CJKOREAEXPRESS"
      name: "大韩通运"
    - code: "JGWL"
      name: "景光物流"
    - code: "CJEXPRESS"
      name: "长江国际速递"
    - code: "CITY56"
      name: "城市映急"
    - code: "CHT361"
      name: "诚和通"
    - code: "ONEEXPRESS"
      name: "一速递"
    - code: "XDEXPRESS"
      name: "迅达速递"
    - code: "BN"
      name: "笨鸟国际"
    - code: "NSF"
      name: "新顺丰国际速递"
    - code: "EPOST"
      name: "韩国邮政"
    - code: "JUMSTC"
      name: "聚盟共建"
    - code: "TAQBINJP"
      name: "Yamato宅急便"
    - code: "A4PX"
      name: "转运四方"
    - code: "DEKUN"
      name: "德坤"
    - code: "COE"
      name: "COE东方快递"
    - code: "DFWL"
      name: "达发物流"
    - code: "TZKY"
      name: "铁中快运"
    - code: "LYT"
      name: "联运通物流"
    - code: "DHLGLOBALLOGISTICS"
      name: "DHL全球货运"
    - code: "SWEDENPOST"
      name: "瑞典邮政"
    - code: "BEEBIRD"
      name: "锋鸟物流"
    - code: "CFWL"
      name: "春风物流"
    - code: "JYWL"
      name: "佳怡物流"
    - code: "XYJ"
      name: "西邮寄"
    - code: "LINGSONG"
      name: "领送送"
    - code: "SJA56"
      name: "四季安物流"
    - code: "WTP"
      name: "微特派"
    - code: "HAOXIANGWULIU"
      name: "豪翔物流"
    - code: "HCT"
      name: "新竹物流HCT"
    - code: "SUYD56"
      name: "速邮达物流"
    - code: "YBWL"
      name: "优拜物流"
    - code: "COSCO"
      name: "中远e环球"
    - code: "GOEX"
      name: "时安达速递"
    - code: "IADLYYZ"
      name: "澳大利亚邮政"
    - code: "LHTEX"
      name: "联昊通"
    - code: "LNET"
      name: "新易泰"
    - code: "WJWL"
      name: "万家物流"
    - code: "AX"
      name: "安迅物流"
    - code: "CCES"
      name: "CCES/国通快递"
    - code: "DPD"
      name: "DPD"
    - code: "FAMIPORT"
      name: "全家快递"
    - code: "HJWL"
      name: "汇捷物流"
    - code: "HNTLWL"
      name: "泰联物流"
    - code: "HQSY"
      name: "环球速运"
    - code: "JTEXPRESS"
      name: "J&TExpress"
    - code: "KEJIE"
      name: "科捷物流"
    - code: "KZWL"
      name: "科紫物流"
    - code: "MHKD"
      name: "民航快递"
    - code: "SHPOST"
      name: "同城快寄"
    - code: "SINGAPOREPOST"
      name: "新加坡邮政"
    - code: "SINGAPORESPEEDPOST"
      name: "新加坡特快专递"
    - code: "STSD"
      name: "三态速递"
    - code: "UPSEN"
      name: "UPS-全球件"
    - code: "WJK"
      name: "万家康"
    - code: "XCWL"
      name: "迅驰物流"
    - code: "XLOBO"
      name: "贝海国际速递"
    - code: "YYSD"
      name: "优优速递"

  # 对象存储配置
  storage:
    # 当前工作的对象存储模式，分别是local、aliyun、tencent、qiniu
    active: local
    # 本地对象存储配置信息
    local:
      storagePath: storage
      # 这个地方应该是wx模块的WxStorageController的fetch方法对应的地址
      address: https://www.zhangcde.asia/wx/storage/fetch/
